server:
  port: 8181
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          username:
          password:
          uri: https://github.com/bogdig/SpringcloudConfig
          search-paths: respo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8183/eureka/

          #spring.cloud.config.server.git.uri：配置git仓库地址
          #spring.cloud.config.server.git.searchPaths：配置仓库路径
          #spring.cloud.config.label：配置仓库的分支
          #spring.cloud.config.server.git.username：访问git仓库的用户名
          #spring.cloud.config.server.git.password：访问git仓库的用户密码